### ISSUE TITLE
--account-tokens issue

### ISSUE THREAD

**Issue by briviere** [cantino/reckon#51]
I wish I new ruby better (Learning) so that I could fix this issue myself and contribute back to this great Ledger tool.

I have the following test.yaml:

Expenses:
  Dining:
    Coffee:
      - 'STARBUCKS'
      - 'TIM HORTON'
    Resturant:
      - 'WENDY''S'
      - 'SUBWAY'
      - 'BARAKAT'

I have the following CSV:

01/09/2015,05354 SUBWAY,8.19,,1000.00
02/18/2015,WENDY'S #6338,8.55,,1000.00
02/25/2015,WENDY'S #6338,8.55,,1000.00
02/25/2015,WENDY'S #6338,9.14,,1000.00
02/27/2015,WENDY'S #6338,5.85,,1000.00
03/09/2015,WENDY'S #6338,17.70,,1000.00
03/16/2015,WENDY'S #6338,11.15,,1000.00
03/23/2015,WENDY'S,10.12,,1000.00

I run the following:

reckon --unattended -o test.dat -f test.csv --account Assets:Chequing --account-tokens test.yaml --ignore-columns 5

Reckon does not find a match for the SUBWAY and the last "WENDY'S" transaction.

The test.dat ledger generated:

2015/01/09  05354 SUBWAY;
    Assets:Chequing                  $8.19
    Income:Unknown                   -$8.19

2015/02/18  WENDY'S #6338;
    Assets:Chequing                  $8.55
    Expenses:Dining:Resturant                    -$8.55

2015/02/25  WENDY'S #6338;
    Assets:Chequing                  $8.55
    Expenses:Dining:Resturant                    -$8.55

2015/02/25  WENDY'S #6338;
    Assets:Chequing                  $9.14
    Expenses:Dining:Resturant                    -$9.14

2015/02/27  WENDY'S #6338;
    Assets:Chequing                  $5.85
    Expenses:Dining:Resturant                    -$5.85

2015/03/09  WENDY'S #6338;
    Assets:Chequing                  $17.70
    Expenses:Dining:Resturant                    -$17.70

2015/03/16  WENDY'S #6338;
    Assets:Chequing                  $11.15
    Expenses:Dining:Resturant                    -$11.15

2015/03/23  WENDY'S;
    Assets:Chequing                  $10.12
    Income:Unknown                   -$10.12

**Comment by cantino** [comment]
Hey @briviere!  @vzctl added the token support so he may have ideas about this.

**Comment by vzctl** [comment]
@briviere, thanks for reporting the bug. I implemented a fix and described the root cause in https://github.com/cantino/reckon/pull/52.

**Comment by briviere** [comment]
#52 has not fixed this issue:

I wish I new ruby better (Learning) so that I could fix this issue myself and contribute back to this great Ledger tool.

I have the following test.yaml:

Expenses:
Dining:
Coffee:
- 'STARBUCKS'
- 'TIM HORTON'
Resturant:
- 'WENDY''S'
- 'SUBWAY'
- 'BARAKAT'

I have the following CSV:

01/09/2015,05354 SUBWAY,8.19,,1000.00
02/18/2015,WENDY'S #6338,8.55,,1000.00
02/25/2015,WENDY'S #6338,8.55,,1000.00
02/25/2015,WENDY'S #6338,9.14,,1000.00
02/27/2015,WENDY'S #6338,5.85,,1000.00
03/09/2015,WENDY'S #6338,17.70,,1000.00
03/16/2015,WENDY'S #6338,11.15,,1000.00
03/23/2015,WENDY'S,10.12,,1000.00

I run the following:

reckon --unattended -o test.dat -f test.csv --account Assets:Chequing --account-tokens test.yaml --ignore-columns 5

Reckon does not find a match for the SUBWAY and the last "WENDY'S" transaction.

The test.dat ledger generated:

2015/01/09 05354 SUBWAY;
Assets:Chequing $8.19
Income:Unknown -$8.19

2015/02/18 WENDY'S #6338;
Assets:Chequing $8.55
Expenses:Dining:Resturant -$8.55

2015/02/25 WENDY'S #6338;
Assets:Chequing $8.55
Expenses:Dining:Resturant -$8.55

2015/02/25 WENDY'S #6338;
Assets:Chequing $9.14
Expenses:Dining:Resturant -$9.14

2015/02/27 WENDY'S #6338;
Assets:Chequing $5.85
Expenses:Dining:Resturant -$5.85

2015/03/09 WENDY'S #6338;
Assets:Chequing $17.70
Expenses:Dining:Resturant -$17.70

2015/03/16 WENDY'S #6338;
Assets:Chequing $11.15
Expenses:Dining:Resturant -$11.15

2015/03/23 WENDY'S;
Assets:Chequing $10.12
Income:Unknown -$10.12

**Comment by vzctl** [comment]
Hi, I just tested your data with the recent released version: reckon-0.4.3 and it works just fine. Could you double-check if you are using the recent version? Looking at the `;` in the transaction descriptions, you have not updated and have not received the patch which fixes the problem.

**Comment by benprew** [comment]
I added a regression test for this, which passes.  I'm closing this issue.
